name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
  addon:
    name: Home Assistant add-on
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1
      - name: Run Home Assistant add-on linter
        uses: frenck/action-addon-linter@v2.21
        with:
          path: ./availability_index

  tests:
    name: Availability index tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7.0.1
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Run unit tests
        run: python3 -m unittest discover -s availability_index/tests -v
